# ==========================================
# Core
# ==========================================
spring.application.name=pocketcare
spring.config.import=optional:file:.env[.properties]
server.servlet.context-path=/api/v1

# ==========================================
# Database Configuration
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ==========================================
# JPA / Hibernate Settings
# ==========================================
# spring.jpa.show-sql=true
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Custom Application Properties
# ==========================================
app.api.timeout-ms=5000
app.features.enable-refunds=true